outfile = open("scriptGenerated.txt",'w')

outfile.truncate(0)

outfile.write("//This script is generated by the scriptGenerator.py \n//for setting intersection normal\n")


#############


for i in range(0,900):
    outfile.write("\tif (intersectIndex == {}) {intersectNormal = uNormals[{}];}\n".format(i,i))




#############

outfile.close()

